// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BuildingDataInput struct {
	Building   string `json:"building"`
	MaxDate    int    `json:"maxDate"`
	MinDate    int    `json:"minDate"`
	EnergyType string `json:"energyType"`
}
